---
plugin:
  name: "monitoring-plugin"
  description: ""
  image: ""
  imagePullPolicy: IfNotPresent
  replicas: 2
  port: 9443
  securityContext:
    enabled: true
  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
  basePath: /
  certificateSecretName: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  acm:
    name: monitoring-console-plugin
    enabled: false
    alertmanager:
      url: https://alertmanager.open-cluster-management-observability.svc:9095
      pluginPort: 9444
    thanos:
      url: https://rbac-query-proxy.open-cluster-management-observability.svc:8443
      pluginPort: 9445
  patcherServiceAccount:
    create: true
    annotations: {}
    name: "monitoring-console-plugin-patcher"
  jobs:
    patchConsoles:
      enabled: true
      image: "registry.redhat.io/openshift4/ose-tools-rhel8@sha256:af22cf89b7f1791b943f507d15c62ed5265d7390b24ab598eefe34f63c07fa9d"
      podSecurityContext:
        enabled: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        enabled: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
